name: easeflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0   # latest stable in 2.x series
  firebase_auth: ^6.1.4    # compatible with firebase_core 2.x
  http: ^1.1.0

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

  # HTTP requests to backend
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/easeflow.png
    - .env